<template>
  <div
    class="connection-guide-backdrop"
    data-connection-guide
    @click.self="emit('close')"
  >
    <section
      ref="dialog"
      class="connection-guide-dialog"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="titleId"
      tabindex="-1"
      @keydown="handleKeydown"
    >
      <header class="connection-guide-header">
        <div>
          <span class="connection-guide-kicker">Connection guide</span>
          <h3 :id="titleId">{{ title }}</h3>
        </div>
        <button
          ref="closeButton"
          type="button"
          class="connection-guide-close"
          data-close-guide
          aria-label="Close connection guide"
          @click="emit('close')"
        >×</button>
      </header>

      <div v-if="topic === 'webhooks'" class="connection-guide-body">
        <div class="connection-guide-callout">
          <strong>You provide the destination.</strong>
          <p>The webhook URL is the public HTTPS endpoint in your other system. It is not an URL generated by FCHub.</p>
        </div>

        <ol class="connection-guide-steps" aria-label="Webhook setup steps">
          <li><span>1</span><div><strong>Add one endpoint</strong><p>Name the receiver and paste its public HTTPS URL. Each receiver is managed independently.</p></div></li>
          <li><span>2</span><div><strong>Generate its signing secret</strong><p>Copy the one-time secret into that receiver. No other endpoint shares it.</p></div></li>
          <li><span>3</span><div><strong>Send a one-shot test</strong><p>The test uses the production signature contract, but a failed test never enters the retry queue.</p></div></li>
          <li><span>4</span><div><strong>Activate the endpoint</strong><p>Activation unlocks after a 2xx test response. Pause it whenever delivery should stop.</p></div></li>
        </ol>

        <section class="connection-guide-block">
          <span class="connection-guide-label">Events sent</span>
          <div class="connection-guide-code-list">
            <code>grant_created</code>
            <code>grant_revoked</code>
            <code>grant_expired</code>
            <code>grant_paused</code>
            <code>grant_resumed</code>
          </div>
        </section>

        <section class="connection-guide-block">
          <span class="connection-guide-label">Receiver contract</span>
          <dl class="connection-guide-contract">
            <div><dt><code>X-FCHub-Signature</code></dt><dd>HMAC-SHA256 of the exact raw JSON body using your signing secret.</dd></div>
            <div><dt><code>X-FCHub-Delivery</code></dt><dd>Stable event ID. Store it and ignore duplicates before applying side effects.</dd></div>
            <div><dt>Delivery</dt><dd>Events are delivered at least once. Failed and non-2xx attempts retry up to seven total attempts.</dd></div>
          </dl>
        </section>
      </div>

      <div v-else class="connection-guide-body">
        <div class="connection-guide-callout">
          <strong>Read-only by design.</strong>
          <p>This key checks whether a member can access a plan or resource. It cannot create or edit memberships.</p>
        </div>

        <section class="connection-guide-block">
          <span class="connection-guide-label">Access check endpoint</span>
          <div class="connection-guide-copy-row">
            <code data-api-endpoint>{{ apiEndpoint }}</code>
            <button
              type="button"
              class="connection-guide-copy"
              data-copy-api-endpoint
              @click="copyApiEndpoint"
            >{{ endpointCopied ? 'Copied' : 'Copy URL' }}</button>
          </div>
          <p v-if="copyError" class="connection-guide-error" role="alert">{{ copyError }}</p>
        </section>

        <section class="connection-guide-block">
          <span class="connection-guide-label">Example request</span>
          <pre><code>{{ apiExample }}</code></pre>
          <p>Send exactly one member identity: <code>email</code> or <code>user_id</code>. Then check either a <code>plan</code>, or a <code>resource_type</code> with <code>resource_id</code>.</p>
        </section>

        <section class="connection-guide-block">
          <span class="connection-guide-label">Which credential goes where?</span>
          <dl class="connection-guide-contract">
            <div><dt>Access checks</dt><dd>Use the generated FCHub key in the <code>X-API-Key</code> header.</dd></div>
            <div><dt>Membership writes</dt><dd>Use WordPress Application Passwords over HTTPS and send an <code>Idempotency-Key</code> with each mutation.</dd></div>
          </dl>
        </section>
      </div>

      <footer class="connection-guide-footer">
        <span>No credentials are displayed in this guide.</span>
        <button type="button" class="connection-guide-done" @click="emit('close')">Got it</button>
      </footer>
    </section>
  </div>
</template>

<script setup>
import { computed, nextTick, onMounted, ref } from 'vue'

const props = defineProps({
  topic: {
    type: String,
    required: true,
    validator: (value) => ['webhooks', 'api'].includes(value),
  },
  apiRoot: {
    type: String,
    required: true,
  },
})

const emit = defineEmits(['close'])
const dialog = ref(null)
const closeButton = ref(null)
const endpointCopied = ref(false)
const copyError = ref('')

const title = computed(() => (
  props.topic === 'webhooks' ? 'Connect a webhook receiver' : 'Connect to the Access API'
))
const titleId = computed(() => `connection-guide-${props.topic}-title`)
const normalisedApiRoot = computed(() => `${String(props.apiRoot || '').replace(/\/+$/, '')}/`)
const apiEndpoint = computed(() => `${normalisedApiRoot.value}check-access`)
const apiExample = computed(() => [
  `curl --get "${apiEndpoint.value}" \\`,
  '  -H "X-API-Key: <your-api-key>" \\',
  '  --data-urlencode "email=member@example.com" \\',
  '  --data-urlencode "plan=pro"',
].join('\n'))

onMounted(() => {
  nextTick(() => closeButton.value?.focus())
})

async function copyApiEndpoint() {
  try {
    await navigator.clipboard.writeText(apiEndpoint.value)
    endpointCopied.value = true
    copyError.value = ''
  } catch {
    endpointCopied.value = false
    copyError.value = 'Copy failed. Select the URL and copy it manually.'
  }
}

function handleKeydown(event) {
  if (event.key === 'Escape') {
    event.preventDefault()
    emit('close')
    return
  }
  if (event.key !== 'Tab' || !dialog.value) return

  const controls = [...dialog.value.querySelectorAll('button:not([disabled])')]
  if (!controls.length) return

  const first = controls[0]
  const last = controls[controls.length - 1]
  const active = document.activeElement
  const wrapsBackward = event.shiftKey && (active === first || !dialog.value.contains(active))
  const wrapsForward = !event.shiftKey && (active === last || !dialog.value.contains(active))

  if (!wrapsBackward && !wrapsForward) return
  event.preventDefault()
  ;(event.shiftKey ? last : first).focus()
}
</script>

<style scoped>
.connection-guide-backdrop { position: fixed; z-index: 100090; inset: 0; display: grid; place-items: center; padding: 18px; background: rgb(15 23 42 / 55%); }
.connection-guide-dialog { width: min(100%, 680px); max-height: calc(100vh - 36px); overflow-y: auto; border-radius: 14px; color: var(--fchub-text-primary); background: var(--fchub-card-bg, #fff); box-shadow: 0 24px 60px rgb(0 0 0 / 22%); }
.connection-guide-dialog:focus { outline: none; }
.connection-guide-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 18px; padding: 22px 24px 18px; border-bottom: 1px solid var(--fchub-border-color); }
.connection-guide-kicker, .connection-guide-label { display: block; color: var(--el-color-primary); font-size: 10px; font-weight: 750; letter-spacing: .08em; text-transform: uppercase; }
.connection-guide-header h3 { margin: 5px 0 0; font-size: 20px; line-height: 1.25; }
.connection-guide-close { flex: 0 0 auto; display: grid; place-items: center; width: 32px; height: 32px; padding: 0; border: 1px solid transparent; border-radius: 8px; color: var(--fchub-text-secondary); background: transparent; font: 24px/1 sans-serif; cursor: pointer; }
.connection-guide-close:hover, .connection-guide-close:focus-visible { border-color: var(--fchub-border-color); color: var(--fchub-text-primary); background: var(--fchub-page-bg); }
.connection-guide-close:focus-visible, .connection-guide-copy:focus-visible, .connection-guide-done:focus-visible { outline: 2px solid var(--el-color-primary); outline-offset: 2px; }
.connection-guide-body { display: grid; gap: 18px; padding: 20px 24px 22px; }
.connection-guide-callout { padding: 14px 16px; border: 1px solid color-mix(in srgb, var(--el-color-primary) 24%, var(--fchub-border-color)); border-radius: 10px; background: color-mix(in srgb, var(--el-color-primary) 6%, var(--fchub-card-bg)); }
.connection-guide-callout strong { font-size: 13px; }
.connection-guide-callout p, .connection-guide-block > p { margin: 4px 0 0; color: var(--fchub-text-secondary); font-size: 12px; line-height: 1.55; }
.connection-guide-steps { display: grid; gap: 10px; margin: 0; padding: 0; list-style: none; }
.connection-guide-steps li { display: grid; grid-template-columns: 28px minmax(0, 1fr); gap: 10px; align-items: start; }
.connection-guide-steps li > span { display: grid; place-items: center; width: 26px; height: 26px; border-radius: 8px; color: var(--el-color-primary); background: color-mix(in srgb, var(--el-color-primary) 11%, var(--fchub-card-bg)); font-size: 11px; font-weight: 750; }
.connection-guide-steps strong { font-size: 12px; }
.connection-guide-steps p { margin: 2px 0 0; color: var(--fchub-text-secondary); font-size: 11px; line-height: 1.5; }
.connection-guide-block { display: grid; gap: 9px; min-width: 0; }
.connection-guide-code-list { display: flex; flex-wrap: wrap; gap: 7px; }
.connection-guide-code-list code, .connection-guide-contract code, .connection-guide-block > p code { padding: 2px 5px; border-radius: 5px; color: var(--fchub-text-primary); background: var(--fchub-page-bg); font-size: 11px; }
.connection-guide-contract { display: grid; gap: 0; margin: 0; border: 1px solid var(--fchub-border-color); border-radius: 9px; overflow: hidden; }
.connection-guide-contract div { display: grid; grid-template-columns: minmax(130px, 180px) minmax(0, 1fr); gap: 14px; padding: 10px 12px; border-bottom: 1px solid var(--fchub-border-color); }
.connection-guide-contract div:last-child { border-bottom: 0; }
.connection-guide-contract dt, .connection-guide-contract dd { margin: 0; font-size: 11px; line-height: 1.5; }
.connection-guide-contract dt { color: var(--fchub-text-primary); font-weight: 650; }
.connection-guide-contract dd { color: var(--fchub-text-secondary); }
.connection-guide-copy-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; align-items: stretch; }
.connection-guide-copy-row > code, .connection-guide-block pre { min-width: 0; margin: 0; padding: 11px 12px; border-radius: 8px; color: var(--fchub-text-primary); background: var(--fchub-page-bg); font: 600 11px/1.55 ui-monospace, SFMono-Regular, Menlo, monospace; overflow-wrap: anywhere; white-space: pre-wrap; }
.connection-guide-copy { min-height: 36px; padding: 6px 11px; border: 1px solid var(--fchub-border-color); border-radius: 8px; color: var(--fchub-text-primary); background: var(--fchub-card-bg); font: inherit; font-size: 11px; font-weight: 650; cursor: pointer; }
.connection-guide-copy:hover { border-color: var(--el-color-primary); color: var(--el-color-primary); }
.connection-guide-error { margin: 0 !important; color: var(--el-color-danger) !important; }
.connection-guide-footer { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 14px 24px; border-top: 1px solid var(--fchub-border-color); background: color-mix(in srgb, var(--fchub-page-bg) 52%, var(--fchub-card-bg)); }
.connection-guide-footer span { color: var(--fchub-text-secondary); font-size: 10px; }
.connection-guide-done { min-height: 34px; padding: 6px 14px; border: 1px solid var(--el-color-primary); border-radius: 8px; color: #fff; background: var(--el-color-primary); font: inherit; font-size: 11px; font-weight: 700; cursor: pointer; }

@media (max-width: 600px) {
  .connection-guide-backdrop { place-items: end stretch; padding: 0; }
  .connection-guide-dialog { width: 100%; max-height: calc(100vh - 24px); border-radius: 14px 14px 0 0; }
  .connection-guide-header, .connection-guide-body { padding-right: 18px; padding-left: 18px; }
  .connection-guide-contract div { grid-template-columns: 1fr; gap: 4px; }
  .connection-guide-copy-row { grid-template-columns: 1fr; }
  .connection-guide-copy { justify-self: start; }
  .connection-guide-footer { align-items: flex-start; padding: 14px 18px; }
}
</style>
